[package]
name = "gh-tui"
version = "0.1.0"
description = "A keyboard first Github TUI"
authors = ["Tenzin Platter <143778894+TenzinPlatter@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["unstable"] }

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
